# Generated by Django 4.2.6 on 2023-12-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_cargo', models.CharField(max_length=99, unique=True)),
                ('estado_cargo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150, unique=True)),
                ('nit', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('telefono1', models.IntegerField()),
                ('telefono2', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_modulo', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=200, null=True)),
                ('url_img', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_modulo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='myapp.modulos')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipodocumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDoc', models.CharField(max_length=99)),
                ('denominacion', models.CharField(max_length=5, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('vencido', models.BooleanField(default=False)),
                ('documento_num', models.IntegerField()),
                ('documento_num_cryp', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.SmallAutoField(primary_key=True, serialize=False)),
                ('detalle_rol', models.CharField(max_length=100)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('permiso_insertar', models.BooleanField(default=True)),
                ('permiso_eliminar', models.BooleanField(default=True)),
                ('permiso_actualizar', models.BooleanField(default=True)),
                ('permiso_consultar', models.BooleanField(default=True)),
                ('permiso_reportes', models.BooleanField(default=True)),
                ('estado_permiso', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.modulos')),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('num_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=99)),
                ('apellidos', models.CharField(max_length=99)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cargo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cargos')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas')),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roles')),
                ('tipo_documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='cargos',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas'),
        ),
    ]
