# Generated by Django 4.2.6 on 2023-12-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_imagenusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='documento_num',
        ),
        migrations.RemoveField(
            model_name='login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ImagenUsuario',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
