# Generated by Django 5.0 on 2024-01-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_login_imagenusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptoFuec',
            fields=[
                ('id_fuec', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fuec', models.CharField(max_length=99)),
                ('modificaciones', models.CharField(max_length=500, null=True)),
                ('num_bus', models.IntegerField(max_length=5)),
                ('num_viaje', models.IntegerField(max_length=9)),
                ('user_creo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
