# Generated by Django 5.0 on 2024-01-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_rptofuec_num_bus_alter_rptofuec_num_viaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenUsuario',
        ),
    ]
