# Generated by Django 5.0 on 2024-01-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_colaboradores_cargo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargos',
        ),
    ]
