# Generated by Django 5.0 on 2024-02-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_cargos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='direccion',
            new_name='oficina',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='ciudad',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
