# Generated by Django 5.0 on 2024-07-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_colaboradores_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='documento_num',
        ),
        migrations.RemoveField(
            model_name='login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ImagenUsuario',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
