# Generated by Django 5.0 on 2024-08-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_fingerprint_login_imagenusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
