# Generated by Django 5.0 on 2024-08-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id_fingerprint', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fingerprint_data', models.BinaryField()),
                ('fingerprint_data_hash', models.CharField(max_length=64)),
            ],
        ),
    ]
