# Generated by Django 5.0 on 2024-08-17 11:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Faceidcolaboradores',
            fields=[
                ('id_faceid', models.AutoField(primary_key=True, serialize=False)),
                ('face_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=5)),
                ('colaborador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('num_vehiculo', models.CharField(max_length=7)),
                ('placa', models.CharField(max_length=7)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas')),
            ],
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='vehiculo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vehiculos'),
        ),
    ]
