# Generated by Django 5.0 on 2024-08-18 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_colaboradores_email_faceidcolaboradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='face_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=5),
        ),
        migrations.DeleteModel(
            name='Faceidcolaboradores',
        ),
    ]
