# Generated by Django 5.0 on 2024-08-18 23:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_colaboradores_face_ids_delete_faceidcolaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='face_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.roles'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='tipo_documento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.tipodocumento'),
        ),
    ]
