# Generated by Django 5.0 on 2024-08-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_events_colaboradores_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
