# Generated by Django 5.0 on 2024-08-23 03:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('event_data', models.JSONField(blank=True, default=list)),
                ('event_participants', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('event_guests', models.JSONField(blank=True, default=list)),
                ('event_actions', models.JSONField(blank=True, default=list)),
                ('event_evidence', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
