# Generated by Django 5.0 on 2024-08-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_events_event_participants_delete_imagenusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('headquarters_name', models.CharField(max_length=259)),
                ('headquarters_address', models.CharField(max_length=259)),
                ('headquarters_departament', models.CharField(max_length=99)),
                ('headquerters_city', models.CharField(max_length=99)),
                ('headquarters_coordinates', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
