# Generated by Django 5.0 on 2024-08-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_headquarters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='roles',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.department'),
        ),
    ]
