# Generated by Django 5.0 on 2024-08-30 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_department_roles_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_title', models.CharField(max_length=255)),
                ('agenda_start_date', models.DateField()),
                ('agenda_end_date', models.DateField()),
                ('agenda_start_time', models.TimeField()),
                ('agenda_end_time', models.TimeField()),
                ('agenda_color', models.CharField(max_length=7)),
                ('agenda_colaborador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('avisos', 'Avisos'), ('mensajes', 'Mensajes'), ('tareas', 'Tareas')], max_length=10)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('expira pronto', 'Expira pronto'), ('no iniciado', 'No iniciado'), ('tardaron 8 días', 'Tardaron 8 días'), ('en curso', 'En curso')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
            ],
        ),
    ]
