# Generated by Django 5.0 on 2024-09-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_events_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_participants',
        ),
    ]
