# Generated by Django 5.0 on 2024-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_events_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_participants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
