# Generated by Django 5.0 on 2024-09-03 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_events_event_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsCategories',
            fields=[
                ('id_training_category', models.AutoField(primary_key=True, serialize=False)),
                ('tr_ctg_name', models.CharField(max_length=99, null=True)),
                ('tr_ctg_abbreviation', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id_training', models.AutoField(primary_key=True, serialize=False)),
                ('training_name', models.CharField()),
                ('training_evaluation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.evaluation')),
                ('training_required_for', models.ManyToManyField(related_name='required_trainings', to='myapp.roles')),
                ('training_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainingscategories')),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradoresTrainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainings')),
            ],
            options={
                'unique_together': {('colaborador', 'training')},
            },
        ),
    ]
