# Generated by Django 5.0 on 2024-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_trainingscategories_trainings_colaboradorestrainings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorestrainings',
            name='notes',
        ),
        migrations.AddField(
            model_name='colaboradorestrainings',
            name='rating',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='colaboradorestrainings',
            name='completion_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
