# Generated by Django 5.0 on 2024-09-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_colaboradorestrainings_notes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colaboradorestrainings',
            unique_together={('colaborador', 'training', 'rating')},
        ),
    ]
