# Generated by Django 5.0 on 2024-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_colaboradorestrainings_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_required_roles',
            field=models.ManyToManyField(related_name='events_required_evaluation', to='myapp.roles'),
        ),
    ]
