# Generated by Django 5.0 on 2024-09-12 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_events_event_required_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_training_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='myapp.trainingscategories'),
        ),
    ]
