# Generated by Django 5.0 on 2024-09-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_events_event_training_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_capacitacion', models.CharField(max_length=255)),
                ('nombre_trabajador', models.CharField(max_length=255)),
                ('cedula_no', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('nombre_capacitador', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('observaciones_iv', models.TextField(blank=True, null=True)),
                ('observaciones_vi', models.TextField(blank=True, null=True)),
                ('preguntas', models.TextField(blank=True, null=True)),
                ('cumplimiento_objetivos', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('claridad_conceptos', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('desarrollo_personal', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('trabajo_actual', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('conocimiento_dominio_tema', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('habilidades_comunicacion', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('capacidad_orientar', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('transmision_ideas_conocimientos', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('manejo_tiempo', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('generacion_empatia', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('puntualidad', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('material_usado', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('recursos_empleados', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('instalaciones', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('aspectos_logisticos', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1)),
                ('firma_capacitador', models.TextField(blank=True, null=True)),
                ('firma_empleado', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id_parte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_preguntas/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_preguntas/')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parte')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_seleccionada', models.CharField(max_length=1)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
            ],
        ),
    ]
