# Generated by Django 5.0 on 2024-09-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_inductiondoc_parte_calificaciontotal_pregunta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InductionDoc',
        ),
    ]
