# Generated by Django 5.0 on 2024-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_inductiondoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='responsable_induccion',
            field=models.CharField(max_length=20),
        ),
    ]
