# Generated by Django 5.0 on 2024-09-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_inductiondoc_cedula_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='cedula_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_colaborador', to='myapp.colaboradores'),
        ),
    ]
