# Generated by Django 5.0 on 2024-09-13 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_inductiondoc_cedula_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='responsable_induccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable_induccion', to='myapp.colaboradores'),
        ),
    ]
