# Generated by Django 5.0 on 2024-09-13 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_alter_inductiondoc_responsable_induccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='cedula_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cedula_empleado', to='myapp.colaboradores'),
        ),
    ]
