# Generated by Django 5.0 on 2024-09-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_inductiondoc_cedula_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='cedula_empleado',
            field=models.CharField(max_length=20),
        ),
    ]
