# Generated by Django 5.0 on 2024-09-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_inductiondoc_cedula_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='responsable_induccion',
            field=models.CharField(max_length=20),
        ),
    ]
