# Generated by Django 5.0 on 2024-09-14 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_inductiondoc_responsable_induccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='cedula_empleado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='responsable_induccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docs_responsable', to='myapp.colaboradores'),
        ),
    ]
