# Generated by Django 5.0 on 2024-09-16 14:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_inductiondoc_cedula_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Sección')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la Sección')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Evaluación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la Evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='face_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=5),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('question', 'Question'), ('headerWithImage', 'Header with Image'), ('headerWithOptions', 'Header with Options'), ('imageOptions', 'Image with Options')], default='question', max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image_src', models.URLField(blank=True, null=True, verbose_name='URL de la Imagen')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Opciones')),
                ('correct_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Respuesta Correcta')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myapp.test'),
        ),
    ]
