# Generated by Django 5.0 on 2024-09-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_section_test_alter_colaboradores_face_ids_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
    ]
