# Generated by Django 5.0 on 2024-09-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_rename_question_text_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True, verbose_name='Enunciado de la Pregunta'),
        ),
    ]
