# Generated by Django 5.0 on 2024-09-16 22:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=455), null=True, size=None),
        ),
    ]
