# Generated by Django 5.0 on 2024-09-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_question_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
