# Generated by Django 5.0 on 2024-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_question_correct_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('alistamiento', 'Alistamiento'), ('conduccion_practica', 'Conducción Práctica'), ('preparacion', 'Preparación')], max_length=20)),
                ('numero', models.IntegerField()),
                ('accion', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
