# Generated by Django 5.0 on 2024-09-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_testdrivers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDrivers',
        ),
    ]
