# Generated by Django 5.0 on 2024-09-19 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_delete_testdrivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrivers',
            fields=[
                ('id_test_driver', models.AutoField(primary_key=True, serialize=False)),
                ('name_driver', models.CharField(max_length=255, null=True)),
                ('dni_driver', models.CharField(max_length=15, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.colaboradores')),
                ('empresa_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.headquarters')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='TestDriversSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('evaluation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testdrivers')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
            ],
        ),
    ]
