# Generated by Django 5.0 on 2024-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_testdrivers_testdriverssession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdrivers',
            old_name='colaborador',
            new_name='colaborador_evaluador',
        ),
        migrations.AddField(
            model_name='testdrivers',
            name='observaciones',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='testdrivers',
            name='recomendacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testdrivers',
            name='resultados',
            field=models.JSONField(default=dict),
        ),
    ]
