# Generated by Django 5.0 on 2024-09-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_rename_colaborador_testdrivers_colaborador_evaluador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrivers',
            name='empresa_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresas'),
        ),
        migrations.AlterField(
            model_name='testdrivers',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vehiculos'),
        ),
        migrations.AlterField(
            model_name='testdriverssession',
            name='evaluation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.testdrivers'),
        ),
        migrations.AlterField(
            model_name='testdriverssession',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.colaboradores'),
        ),
    ]
