# Generated by Django 5.0 on 2024-09-21 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_testdrivers_testdriverssession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSessionResponses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.testdrivers')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenTest',
            fields=[
                ('id_written_test', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.testdrivers')),
            ],
        ),
    ]
