# Generated by Django 5.0 on 2024-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_testsessionresponses_writtentest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivers',
            name='calificaciones',
            field=models.JSONField(default=dict),
        ),
    ]
