# Generated by Django 5.0 on 2024-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_testdrivers_calificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivers',
            name='experience_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testdrivers',
            name='license_category',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
