# Generated by Django 5.0 on 2024-09-24 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_testdrivers_experience_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
