# Generated by Django 5.0 on 2024-09-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_responses', models.JSONField(default=dict)),
                ('current_section', models.IntegerField(default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.testdrivers')),
            ],
        ),
    ]
