# Generated by Django 5.0 on 2024-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_writtentestsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivers',
            name='signature_driver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
