# Generated by Django 5.0 on 2024-09-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_testdrivers_signature_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WrittenTestSession',
        ),
    ]
