# Generated by Django 5.0 on 2024-09-25 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_delete_writtentestsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenTestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_responses', models.JSONField(default=dict)),
                ('current_section', models.IntegerField(default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.testdrivers')),
            ],
        ),
    ]
