# Generated by Django 5.0 on 2024-09-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_writtentestsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiniestroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=10)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='myapp.siniestro')),
            ],
        ),
    ]
