# Generated by Django 5.0 on 2024-10-10 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_alter_siniestro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='empresa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresas'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.department'),
        ),
    ]
