# Generated by Django 5.0 on 2024-10-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_department_empresa_id_alter_roles_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.empresas'),
        ),
    ]
