# Generated by Django 5.0 on 2024-10-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_alter_department_empresa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='exp_documento',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
