# Generated by Django 5.0 on 2024-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0085_remove_events_event_evaluation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_city',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_required_roles',
            field=models.ManyToManyField(null=True, related_name='events_required_evaluation', to='myapp.roles'),
        ),
    ]
