# Generated by Django 5.0 on 2024-10-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0086_remove_event_event_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
    ]
