# Generated by Django 5.0 on 2024-10-11 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0087_remove_event_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.headquarters'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_required_roles',
            field=models.ManyToManyField(related_name='events_required_evaluation', to='myapp.roles'),
        ),
    ]
