# Generated by Django 5.0 on 2024-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_alter_event_event_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='has_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login',
            name='single_use_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
