# Generated by Django 5.0 on 2024-10-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0089_login_expiration_time_login_has_logged_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='rol_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.roles'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='tipo_documento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.tipodocumento'),
        ),
    ]
