# Generated by Django 5.0 on 2024-10-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0090_alter_colaboradores_rol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='apellidos',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nombres',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
