# Generated by Django 5.0 on 2024-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0091_alter_colaboradores_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductiondoc',
            name='id',
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='cedula_empleado',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
