# Generated by Django 5.0 on 2024-10-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0092_remove_inductiondoc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='aspectos_logisticos',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='capacidad_orientar',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='claridad_conceptos',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='conocimiento_tema',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='cumplimiento_objetivos',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='desarrollo_personal',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='generacion_empatia',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='instalaciones',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.headquarters'),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='manejo_tiempo',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='material_usado',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='puntualidad',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='recursos_empleados',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino1',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino10',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino11',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino12',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino13',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino14',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino15',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino16',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino17',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino18',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino19',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino2',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino3',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino4',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino5',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino6',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino7',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino8',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='sino9',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='trabajo_actual',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='transmision_ideas',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
    ]
