# Generated by Django 5.0 on 2024-10-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0093_alter_inductiondoc_aspectos_logisticos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inductiondoc',
            name='habilidades_comunicacion',
            field=models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True),
        ),
    ]
