# Generated by Django 5.0 on 2024-10-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_alter_inductiondoc_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
