# Generated by Django 5.0 on 2024-10-16 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0096_alter_inductiondoc_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='responsable_induccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='docs_responsable', to='myapp.colaboradores'),
        ),
    ]
