# Generated by Django 5.0 on 2024-10-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0097_alter_inductiondoc_responsable_induccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='cedula_empleado',
            field=models.CharField(max_length=99, primary_key=True, serialize=False),
        ),
    ]
