# Generated by Django 5.0 on 2024-10-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0098_alter_inductiondoc_cedula_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductiondoc',
            name='cedula_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.colaboradores'),
        ),
    ]
