# Generated by Django 5.0 on 2024-10-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0099_alter_inductiondoc_cedula_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InductionDoc',
        ),
    ]
