# Generated by Django 5.0 on 2024-10-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0100_delete_inductiondoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionDoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vfanswers', models.JSONField(blank=True, default=dict)),
                ('vfanswers2', models.JSONField(blank=True, default=dict)),
                ('vfanswers3', models.JSONField(blank=True, default=dict)),
                ('abcanswers', models.JSONField(blank=True, default=dict)),
                ('abcanswers2', models.JSONField(blank=True, default=dict)),
                ('abcanswers3', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateField(auto_now=True)),
                ('observaciones_vi', models.TextField(blank=True, null=True)),
                ('observaciones_iv', models.TextField(blank=True, null=True)),
                ('cumplimiento_objetivos', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('claridad_conceptos', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('desarrollo_personal', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('trabajo_actual', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('conocimiento_tema', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], default='', max_length=1, null=True)),
                ('habilidades_comunicacion', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('capacidad_orientar', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], default='', max_length=1, null=True)),
                ('transmision_ideas', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('manejo_tiempo', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], default='', max_length=1, null=True)),
                ('generacion_empatia', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('puntualidad', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('material_usado', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('recursos_empleados', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('instalaciones', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('aspectos_logisticos', models.CharField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('D', 'Deficiente')], max_length=1, null=True)),
                ('sino1', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, null=True)),
                ('sino2', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, null=True)),
                ('sino3', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, null=True)),
                ('sino4', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino5', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino6', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino7', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino8', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino9', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino10', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino11', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino12', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino13', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino14', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino15', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino16', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino17', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino18', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('sino19', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='', max_length=3, null=True)),
                ('cedula_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaboradores')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.headquarters')),
                ('responsable_induccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='docs_responsable', to='myapp.colaboradores')),
            ],
        ),
    ]
