# Generated by Django 5.0 on 2024-10-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0101_inductiondoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='permisos',
            old_name='modulo_id',
            new_name='modulo',
        ),
        migrations.RenameField(
            model_name='permisos',
            old_name='rol_id',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='permiso_actualizar',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='permiso_consultar',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='permiso_eliminar',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='permiso_insertar',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='permiso_reportes',
        ),
        migrations.AddField(
            model_name='permisos',
            name='acciones',
            field=models.ManyToManyField(blank=True, to='myapp.acciones'),
        ),
    ]
