# Generated by Django 5.0 on 2024-10-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0102_acciones_rename_modulo_id_permisos_modulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulos',
            name='url_img',
        ),
    ]
