# Generated by Django 5.0 on 2024-10-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0106_remove_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='agenda_type',
            field=models.CharField(choices=[('work', 'Horario Laboral'), ('event', 'Evento')], default='event', max_length=10),
        ),
    ]
