# Generated by Django 5.0 on 2024-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0107_agenda_agenda_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='left_early',
            field=models.BooleanField(default=False),
        ),
    ]
