# Generated by Django 5.0 on 2024-11-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0108_registroasistencia_is_late_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnteAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='siniestro',
            name='gravedad',
            field=models.CharField(choices=[('Heridos', 'Heridos'), ('Choque simple', 'Choque simple'), ('Muertos', 'Muertos'), ('Heridos y muertos', 'Heridos y muertos')], default='Choque simple', max_length=20),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='numero_victimas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tipo_evento',
            field=models.CharField(choices=[('Siniestro', 'Siniestro'), ('Incidente', 'Incidente')], default='Incidente', max_length=20),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='zona',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urbana', 'Urbana')], default='Rural', max_length=10),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='entes_atendieron',
            field=models.ManyToManyField(null=True, related_name='siniestros', to='myapp.enteatencion'),
        ),
    ]
