# Generated by Django 5.0 on 2024-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0109_enteatencion_siniestro_gravedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='entes_atendieron',
            field=models.ManyToManyField(blank=True, related_name='siniestros', to='myapp.enteatencion'),
        ),
    ]
