# Generated by Django 5.0 on 2024-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0110_alter_siniestro_entes_atendieron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='entes_atendieron',
            field=models.ManyToManyField(related_name='siniestros', to='myapp.enteatencion'),
        ),
    ]
