# Generated by Django 5.0 on 2024-12-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0112_alter_siniestro_latitud_alter_siniestro_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='colaborador',
            field=models.ForeignKey(default=100567890, on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='myapp.colaboradores'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='myapp.empresas'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='myapp.vehiculos'),
        ),
        migrations.AlterField(
            model_name='siniestromedia',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SiniestroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.siniestro')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.colaboradores')),
            ],
        ),
    ]
