# Generated by Django 5.0 on 2024-12-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0113_siniestro_colaborador_siniestro_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestromedia',
            name='tipo',
            field=models.CharField(max_length=150),
        ),
    ]
