# Generated by Django 5.0 on 2024-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0116_event_is_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_required_colaboradores',
            field=models.ManyToManyField(blank=True, related_name='events_required_evaluation', to='myapp.colaboradores'),
        ),
    ]
