# Generated by Django 5.0 on 2024-12-16 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0117_event_event_required_colaboradores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventevidence',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventevidence',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='evidences',
            field=models.ManyToManyField(blank=True, default=[], related_name='events', to='myapp.eventevidence'),
        ),
        migrations.AddField(
            model_name='eventevidence',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
