# Generated by Django 5.0 on 2024-12-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0118_remove_eventevidence_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_required_colaboradores',
        ),
        migrations.RemoveField(
            model_name='event',
            name='evidences',
        ),
        migrations.RemoveField(
            model_name='eventevidence',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='eventevidence',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='myapp.event'),
            preserve_default=False,
        ),
    ]
