# Generated by Django 5.0 on 2024-12-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0119_remove_event_event_required_colaboradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventevidence',
            name='evidence_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
