# Generated by Django 5.0 on 2024-12-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0120_eventevidence_evidence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_required_colaboradores',
            field=models.ManyToManyField(blank=True, null=True, related_name='events_required_colaboradores', to='myapp.colaboradores'),
        ),
    ]
