# Generated by Django 5.0 on 2024-12-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0121_event_event_required_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='carroceria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='chasis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='cilindraje',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='ciudadBase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='clase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='combustible',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='licenciaTransito',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='modelo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='numeroEjes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='numeroMotor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='paxLt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='paxRl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='serie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='tipoLinea',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='tipoMotor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='unionTemporal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='vin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_required_colaboradores',
            field=models.ManyToManyField(related_name='events_required_colaboradores', to='myapp.colaboradores'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='num_vehiculo',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='placa',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='ConductorAsociado',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
                ('fechaAsignacion', models.DateField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores_asociados', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_facturacion', models.AutoField(primary_key=True, serialize=False)),
                ('facturaNumero', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id_ficha_tecnica', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaTransito',
            fields=[
                ('id_licencia_transito', models.AutoField(primary_key=True, serialize=False)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='licencia_transito/')),
                ('numero', models.CharField(max_length=100)),
                ('fechaExpedicion', models.DateField()),
                ('fechaInicialVigencia', models.DateField()),
                ('fechaFinVigencia', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencia_transito', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(max_length=150)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='NovedadVehiculo',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaNovedad', models.DateField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_vehiculo', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id_poliza', models.AutoField(primary_key=True, serialize=False)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='polizas/')),
                ('numeroDocumento', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('fechaExpedicion', models.DateField()),
                ('fechaInicioVigencia', models.DateField()),
                ('fechaFinVigencia', models.DateField()),
                ('nitAseguradora', models.CharField(max_length=100)),
                ('nombreAseguradora', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoJuridico',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_juridicos', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaIngreso', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('tipoDocumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionTecnomecanica',
            fields=[
                ('id_revision', models.AutoField(primary_key=True, serialize=False)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='revision_tecnomecanica/')),
                ('numero', models.CharField(max_length=100)),
                ('fechaExpedicion', models.DateField()),
                ('fechaInicialVigencia', models.DateField()),
                ('fechaFinVigencia', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_tecnomecanica', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('numeroInterno', models.IntegerField()),
                ('empresaOficial', models.CharField(max_length=150)),
                ('empresaAdministra', models.CharField(max_length=150)),
                ('tipoOperacion', models.CharField(max_length=150)),
                ('nivelServicio', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaIngreso', models.DateField()),
                ('fechaFinServicio', models.DateField(blank=True, null=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Soat',
            fields=[
                ('id_soat', models.AutoField(primary_key=True, serialize=False)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='soat/')),
                ('numero', models.CharField(max_length=100)),
                ('fechaExpedicion', models.DateField()),
                ('fechaInicialVigencia', models.DateField()),
                ('fechaFinVigencia', models.DateField()),
                ('nitAseguradora', models.CharField(max_length=100)),
                ('nombreAseguradora', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soat', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaOperacion',
            fields=[
                ('id_tarjeta_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='tarjeta_operacion/')),
                ('numero', models.CharField(max_length=100)),
                ('fechaExpedicion', models.DateField()),
                ('fechaInicialVigencia', models.DateField()),
                ('fechaFinVigencia', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_operacion', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Tenedor',
            fields=[
                ('id_tenedor', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaIngreso', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('tipoDocumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenedores', to='myapp.vehiculos')),
            ],
        ),
    ]
