# Generated by Django 5.0 on 2024-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0123_carroceria_categoria_ciudad_clasevehiculo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='tipoLinea',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
