# Generated by Django 5.0 on 2024-12-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0124_alter_vehiculos_tipolinea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='num_vehiculo',
        ),
    ]
