# Generated by Django 4.2.17 on 2025-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0126_notification_is_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revisiontecnomecanica",
            old_name="fechaExpedicion",
            new_name="fecha_expedicion",
        ),
        migrations.RenameField(
            model_name="revisiontecnomecanica",
            old_name="fechaFinVigencia",
            new_name="fecha_vencimiento",
        ),
        migrations.RenameField(
            model_name="soat",
            old_name="fechaExpedicion",
            new_name="fecha_expedicion",
        ),
        migrations.RenameField(
            model_name="soat",
            old_name="fechaFinVigencia",
            new_name="vigencia_desde",
        ),
        migrations.RenameField(
            model_name="soat",
            old_name="fechaInicialVigencia",
            new_name="vigencia_hasta",
        ),
        migrations.RemoveField(
            model_name="revisiontecnomecanica",
            name="fechaInicialVigencia",
        ),
        migrations.RemoveField(
            model_name="revisiontecnomecanica",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="soat",
            name="nitAseguradora",
        ),
        migrations.RemoveField(
            model_name="soat",
            name="nombreAseguradora",
        ),
        migrations.RemoveField(
            model_name="soat",
            name="numero",
        ),
        migrations.AddField(
            model_name="propietario",
            name="porcentaje",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="revisiontecnomecanica",
            name="no_certificado",
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="revisiontecnomecanica",
            name="placa",
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="soat",
            name="numero_poliza",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="soat",
            name="placa",
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenedor",
            name="porcentaje",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="revisiontecnomecanica",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="revisiontecnomecanica",
            name="soporte",
            field=models.CharField(default=1, max_length=299),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="soat",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="soat",
            name="soporte",
            field=models.CharField(default=1, max_length=299),
            preserve_default=False,
        ),
    ]
