# Generated by Django 4.2.17 on 2025-01-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0127_rename_fechaexpedicion_revisiontecnomecanica_fecha_expedicion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenedor",
            name="fechaIngreso",
            field=models.DateField(auto_now_add=True),
        ),
    ]
