# Generated by Django 4.2.17 on 2025-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0128_alter_tenedor_fechaingreso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propietario",
            name="fechaIngreso",
            field=models.DateField(auto_now_add=True),
        ),
    ]
