# Generated by Django 4.2.17 on 2025-01-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0129_alter_propietario_fechaingreso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculos",
            name="id_vehiculo",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
