# Generated by Django 4.2.17 on 2025-01-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0130_alter_vehiculos_id_vehiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siniestro",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siniestros",
                to="myapp.colaboradores",
            ),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siniestros",
                to="myapp.empresas",
            ),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siniestros",
                to="myapp.vehiculos",
            ),
        ),
    ]
