# Generated by Django 4.2.17 on 2025-01-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0134_alter_evaluation_id_alter_section_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
