# Generated by Django 4.2.17 on 2025-01-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0135_division_description_section_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FillBlank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blank_index", models.PositiveIntegerField(default=0)),
                ("correct_text", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HotspotCoordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left", models.CharField(max_length=255)),
                ("right", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MultiSelectOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OrderingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("score", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="division",
        ),
        migrations.RemoveField(
            model_name="section",
            name="division",
        ),
        migrations.AddField(
            model_name="evaluation",
            name="global_time_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="randomize_answers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="randomize_questions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="feedback_correct",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="feedback_incorrect",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="file_answer",
            field=models.FileField(blank=True, null=True, upload_to="file_answers/"),
        ),
        migrations.AddField(
            model_name="question",
            name="media_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="open_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="rating_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="scenario_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="score",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="time_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Opción Múltiple"),
                    ("true_false", "Verdadero/Falso"),
                    ("open_answer", "Respuesta Abierta"),
                    ("matching", "Matching"),
                    ("ordering", "Ordenamiento"),
                    ("multiple_selection", "Selección Múltiple"),
                    ("rating", "Rating"),
                    ("hotspot", "Hotspot"),
                    ("fill_in_blanks", "Rellenar Espacios"),
                    ("file_upload", "Subir Archivo"),
                    ("scenario", "Escenario"),
                    ("timed", "Cronometrada"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="section",
            name="media_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="section",
            name="evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="myapp.evaluation",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="section",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Division",
        ),
        migrations.AddField(
            model_name="part",
            name="evaluation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="myapp.evaluation",
            ),
        ),
        migrations.AddField(
            model_name="orderingitem",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordering_items",
                to="myapp.question",
            ),
        ),
        migrations.AddField(
            model_name="multiselectoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multi_select_options",
                to="myapp.question",
            ),
        ),
        migrations.AddField(
            model_name="matchingpair",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matching_pairs",
                to="myapp.question",
            ),
        ),
        migrations.AddField(
            model_name="hotspotcoordinate",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotspot_coordinates",
                to="myapp.question",
            ),
        ),
        migrations.AddField(
            model_name="fillblank",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fill_blanks",
                to="myapp.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="myapp.part",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="myapp.part",
            ),
        ),
    ]
