# Generated by Django 4.2.17 on 2025-01-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0136_fillblank_hotspotcoordinate_matchingpair_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inductiondoc",
            name="ciudadFecha",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="ciudad_fecha_autorizacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="firma_autorizacion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="firma_capacitador",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="firma_empleado",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="horafin_pesv",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="horafin_social",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="huella_soci2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inductiondoc",
            name="nombre_autorizacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="part",
            name="evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="myapp.evaluation",
            ),
        ),
    ]
