# Generated by Django 4.2.17 on 2025-02-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0137_inductiondoc_ciudadfecha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siniestro",
            name="ipat",
            field=models.CharField(
                choices=[("Sí", "Sí"), ("No", "No")], default="No", max_length=3
            ),
        ),
    ]
