# Generated by Django 4.2.17 on 2025-02-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0139_alter_siniestro_ipat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicio",
            old_name="categoria",
            new_name="servicio",
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="porcentaje",
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="vehiculo",
        ),
        migrations.RemoveField(
            model_name="tenedor",
            name="porcentaje",
        ),
        migrations.RemoveField(
            model_name="tenedor",
            name="vehiculo",
        ),
        migrations.AlterField(
            model_name="propietario",
            name="identificacion",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tenedor",
            name="identificacion",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="VehiculoTenedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porcentaje", models.IntegerField()),
                (
                    "tenedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos_relations",
                        to="myapp.tenedor",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenedores_relations",
                        to="myapp.vehiculos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiculoPropietario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porcentaje", models.IntegerField()),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos_relations",
                        to="myapp.propietario",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propietarios_relations",
                        to="myapp.vehiculos",
                    ),
                ),
            ],
        ),
    ]
