# Generated by Django 4.2.17 on 2025-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0140_rename_categoria_servicio_servicio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculotenedor",
            name="tenedor",
        ),
        migrations.RemoveField(
            model_name="vehiculotenedor",
            name="vehiculo",
        ),
        migrations.AddField(
            model_name="vehiculos",
            name="propietarios",
            field=models.ManyToManyField(
                blank=True, related_name="vehiculos", to="myapp.propietario"
            ),
        ),
        migrations.AddField(
            model_name="vehiculos",
            name="tenedores",
            field=models.ManyToManyField(
                blank=True, related_name="vehiculos", to="myapp.tenedor"
            ),
        ),
        migrations.DeleteModel(
            name="VehiculoPropietario",
        ),
        migrations.DeleteModel(
            name="VehiculoTenedor",
        ),
    ]
