# Generated by Django 4.2.17 on 2025-02-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0141_remove_vehiculotenedor_tenedor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculos",
            name="propietarios",
        ),
        migrations.RemoveField(
            model_name="vehiculos",
            name="tenedores",
        ),
        migrations.CreateModel(
            name="VehiculoTenedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porcentaje", models.IntegerField()),
                (
                    "tenedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos_relations",
                        to="myapp.tenedor",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenedores_relations",
                        to="myapp.vehiculos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiculoPropietario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porcentaje", models.IntegerField()),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos_relations",
                        to="myapp.propietario",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propietarios_relations",
                        to="myapp.vehiculos",
                    ),
                ),
            ],
        ),
    ]
