# Generated by Django 4.2.17 on 2025-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0142_remove_vehiculos_propietarios_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculos",
            name="id_vehiculo",
        ),
        migrations.AlterField(
            model_name="vehiculos",
            name="placa",
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
