# Generated by Django 4.2.17 on 2025-02-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0145_alter_acciones_id_alter_conductorasociado_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colaboradores",
            old_name="vehiculo_id",
            new_name="vehiculo",
        ),
        migrations.RemoveField(
            model_name="siniestro",
            name="vehiculo",
        ),
    ]
