# Generated by Django 4.2.17 on 2025-02-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0146_rename_vehiculo_id_colaboradores_vehiculo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agenda",
            old_name="agenda_colaborador_id",
            new_name="agenda_colaborador",
        ),
        migrations.RenameField(
            model_name="colaboradores",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="colaboradores",
            old_name="rol_id",
            new_name="rol",
        ),
        migrations.RenameField(
            model_name="colaboradores",
            old_name="tipo_documento_id",
            new_name="tipo_documento",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="roles",
            old_name="department_id",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="roles",
            old_name="empresa_id",
            new_name="empresa",
        ),
        migrations.RenameField(
            model_name="section2",
            old_name="test_id",
            new_name="test",
        ),
        migrations.RenameField(
            model_name="testsessionresponses",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="writtentest",
            old_name="test_driver_id",
            new_name="test_driver",
        ),
        migrations.AddField(
            model_name="siniestro",
            name="vehiculo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siniestros",
                to="myapp.vehiculos",
            ),
        ),
    ]
