# Generated by Django 4.2.17 on 2025-02-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0147_rename_agenda_colaborador_id_agenda_agenda_colaborador_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresas",
            name="id",
            field=models.IntegerField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siniestros",
                to="myapp.colaboradores",
            ),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siniestros",
                to="myapp.empresas",
            ),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="entes_atendieron",
            field=models.ManyToManyField(
                blank=True, related_name="siniestros", to="myapp.enteatencion"
            ),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="latitud",
            field=models.DecimalField(
                blank=True, decimal_places=19, max_digits=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="longitud",
            field=models.DecimalField(
                blank=True, decimal_places=19, max_digits=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="numero_victimas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="siniestro",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siniestros",
                to="myapp.vehiculos",
            ),
        ),
        migrations.CreateModel(
            name="Tercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("cedula", models.CharField(max_length=20)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=150, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "siniestro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terceros",
                        to="myapp.siniestro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActaConciliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo_conductor1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cedula_conductor1",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "placa_conductor1",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("firma_conductor1", models.TextField(blank=True, null=True)),
                (
                    "nombre_completo_conductor2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cedula_conductor2",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "placa_conductor2",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("firma_conductor2", models.TextField(blank=True, null=True)),
                ("conciliacion_lograda", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "siniestro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acta_conciliacion",
                        to="myapp.siniestro",
                    ),
                ),
            ],
        ),
    ]
