# Generated by Django 4.2.17 on 2025-02-25 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0148_alter_empresas_id_alter_siniestro_colaborador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siniestro",
            name="inmovilizacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tercero",
            name="audio_version",
            field=models.FileField(blank=True, null=True, upload_to="terceros/audio/"),
        ),
        migrations.AddField(
            model_name="tercero",
            name="conductor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tercero",
            name="correo_conductor",
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="tercero",
            name="correo_propietario",
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="tercero",
            name="direccion_conductor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tercero",
            name="direccion_propietario",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tercero",
            name="fotos_seguro",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=10,
            ),
        ),
        migrations.AddField(
            model_name="tercero",
            name="licencia_conduccion",
            field=models.FileField(
                blank=True, null=True, upload_to="terceros/licencias/"
            ),
        ),
        migrations.AddField(
            model_name="tercero",
            name="licencia_transito",
            field=models.FileField(
                blank=True, null=True, upload_to="terceros/licencias/"
            ),
        ),
        migrations.AddField(
            model_name="tercero",
            name="propietario",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="empresas",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
