# Generated by Django 4.2.17 on 2025-02-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0149_siniestro_inmovilizacion_tercero_audio_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siniestro",
            name="direccion_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
