# Generated by Django 5.0 on 2025-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0151_conversationsession_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='telefono',
            field=models.CharField(null=True),
        ),
    ]
