# Generated by Django 5.0 on 2025-03-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0152_colaboradores_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vehiculos'),
        ),
    ]
