# Generated by Django 5.0 on 2025-03-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0154_alter_colaboradores_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='vehiculo',
        ),
    ]
