# Generated by Django 5.0 on 2025-03-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0156_colaboradores_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductorasociado',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='facturacion',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='licenciatransito',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='novedadvehiculo',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='procedimientojuridico',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='revisiontecnomecanica',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='soat',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='testdrivers',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='vehiculopropietario',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='vehiculotenedor',
            name='vehiculo',
        ),
    ]
