# Generated by Django 5.0 on 2025-03-02 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0157_remove_conductorasociado_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorasociado',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductores_asociados', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='licenciatransito',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licencia_transito', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='novedadvehiculo',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades_vehiculo', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='procedimientojuridico',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_juridicos', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='revisiontecnomecanica',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_tecnomecanica', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='vehiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='soat',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soat', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='tarjetaoperacion',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_operacion', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='testdrivers',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='vehiculopropietario',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_relations', to='myapp.vehiculos'),
        ),
        migrations.AddField(
            model_name='vehiculotenedor',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenedores_relations', to='myapp.vehiculos'),
        ),
    ]
