# Generated by Django 5.0 on 2025-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0158_conductorasociado_vehiculo_facturacion_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaconciliacion',
            name='email_conductor2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='actaconciliacion',
            name='telefono_conductor2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
