# Generated by Django 5.0 on 2025-03-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0159_actaconciliacion_email_conductor2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaconciliacion',
            name='suma_a_pagar',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
