# Generated by Django 5.0 on 2025-03-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0160_actaconciliacion_suma_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaconciliacion',
            name='pdf_conciliacion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
