# Generated by Django 5.0 on 2025-03-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0161_actaconciliacion_pdf_conciliacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='audio_version',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='licencia_conduccion',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='licencia_transito',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
