# Generated by Django 5.0 on 2025-03-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0162_alter_tercero_audio_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
