# Generated by Django 5.0 on 2025-03-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0163_conversationsession_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='ciudad',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='audio_version',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='licencia_conduccion',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='licencia_transito',
            field=models.CharField(blank=True, null=True),
        ),
    ]
