# Generated by Django 5.0 on 2025-03-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0164_empresas_ciudad_alter_tercero_audio_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='manager_signature',
            field=models.CharField(null=True),
        ),
    ]
