# Generated by Django 5.0 on 2025-03-26 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0165_empresas_manager_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('pdf_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('firmado', models.BooleanField(default=False)),
                ('link_firma', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
