# Generated by Django 5.0 on 2025-03-26 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0166_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CAMBIO_MOTOR', 'Cambio de motor'), ('REGRABACION_MOTOR', 'Regrabación de motor'), ('DUPLICADO_PLACAS', 'Duplicado de placas'), ('DESVINCULACION', 'Desvinculación')], max_length=50)),
                ('pdf_soporte', models.FileField(blank=True, null=True, upload_to='eventos_legales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='myapp.procedimientojuridico')),
            ],
        ),
    ]
