# Generated by Django 5.0 on 2025-03-26 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0167_eventolegal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientojuridico',
            name='estado',
            field=models.CharField(default='En Proceso', max_length=50),
        ),
        migrations.AlterField(
            model_name='procedimientojuridico',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_juridicos', to='myapp.vehiculos'),
        ),
    ]
