# Generated by Django 5.0 on 2025-03-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0168_alter_procedimientojuridico_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventolegal',
            name='procedimiento',
        ),
        migrations.AddField(
            model_name='eventolegal',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_legales', to='myapp.vehiculos'),
            preserve_default=False,
        ),
    ]
