# Generated by Django 5.0 on 2025-03-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0169_remove_eventolegal_procedimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventolegal',
            name='pdf_soporte',
        ),
        migrations.CreateModel(
            name='EventoLegalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='eventos_legales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='myapp.eventolegal')),
            ],
        ),
    ]
