# Generated by Django 5.0 on 2025-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0173_remove_vehiculos_caracteristicasmecanicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='caracteristicasMecanicas',
            field=models.FileField(blank=True, null=True, upload_to='caracteristicas/'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='declaracionImportacion',
            field=models.FileField(blank=True, null=True, upload_to='importaciones/'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='facturaCompra',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
