# Generated by Django 5.0 on 2025-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0175_alter_vehiculos_tipolinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventolegal',
            name='merged_pdf',
            field=models.FileField(blank=True, null=True, upload_to='eventos_legales/merged_pdfs/'),
        ),
    ]
