# Generated by Django 5.0 on 2025-04-03 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0176_eventolegal_merged_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='manager_signature',
            new_name='email_informacion',
        ),
        migrations.AddField(
            model_name='empresas',
            name='email_juridica',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='nombre_empresa_corto',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='representante_firma',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='representante_legal',
            field=models.CharField(null=True),
        ),
        migrations.CreateModel(
            name='EventoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('hurtoOferta', 'Hurto con Oferta'), ('hurtoSinOfertaGeneral', 'Hurto sin Oferta (General)'), ('hurtoSinOferta', 'Hurto sin Oferta'), ('fallaConductor', 'Falla Conductor'), ('peConResponsabilidad', 'PE con Responsabilidad (Sí)'), ('peConResponsabilidadEvidencia', 'PE con Responsabilidad (Sí) c/ Evidencia'), ('paso2', 'Hurto de Equipaje - Paso 2')], max_length=50)),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_eventos/')),
                ('datos_json', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.empresas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='myapp.vehiculos')),
            ],
        ),
    ]
