# Generated by Django 5.0 on 2025-04-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0178_eventodocumento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='audio_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='fotos_seguro',
            field=models.FileField(blank=True, null=True, upload_to='seguros/'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='licencia_conduccion',
            field=models.FileField(blank=True, null=True, upload_to='licencias/'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='licencia_transito',
            field=models.FileField(blank=True, null=True, upload_to='licencias/'),
        ),
    ]
