# Generated by Django 5.0 on 2025-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0179_alter_tercero_audio_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaconciliacion',
            name='conciliacion_por_conciliador',
            field=models.FileField(blank=True, null=True, upload_to='conciliaciones/'),
        ),
    ]
