# Generated by Django 5.0 on 2025-04-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0180_actaconciliacion_conciliacion_por_conciliador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='soporte',
            field=models.CharField(max_length=299),
        ),
    ]
