# Generated by Django 5.0 on 2025-04-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0182_revisiontecnomecanica_chasis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_evento', models.CharField(max_length=100)),
                ('clase_evento_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('choque_con', models.CharField(blank=True, max_length=100, null=True)),
                ('clase_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_fijo', models.CharField(blank=True, max_length=100, null=True)),
                ('diseno_via', models.JSONField(default=list)),
                ('caracteristica_via', models.JSONField(default=list)),
                ('opciones_geometricas', models.JSONField(blank=True, default=list, null=True)),
                ('condicion_climatica', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_impacto', models.JSONField(default=list)),
                ('lugar_impacto_texto', models.TextField(blank=True, null=True)),
                ('lugar_impacto_imagenes', models.JSONField(default=list)),
                ('impact_visual', models.CharField(max_length=50)),
                ('impact_visual_svg', models.FileField(blank=True, null=True, upload_to='ipat_svgs/')),
                ('impact_visual_lines', models.JSONField(default=list)),
                ('victimas', models.TextField(blank=True, null=True)),
                ('hipotesis_text', models.TextField(blank=True, null=True)),
                ('hipotesis_audio', models.JSONField(blank=True, default=list)),
                ('testigos', models.JSONField(blank=True, default=list)),
                ('caracteristicas_lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('zona_escolar', models.BooleanField(default=False)),
                ('tipo_zona_urbana', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipat_record', to='myapp.siniestro')),
            ],
        ),
    ]
