# Generated by Django 5.0 on 2025-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0183_ipat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipat',
            name='alineacion_horizontal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='alineacion_vertical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='calzadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='carriles',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='condicion_vial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='condicion_vial_otra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='control_items',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='control_other',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='control_sub_items',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='controles_transito',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='elementos_laterales',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='estado_vial',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='iluminacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='iluminacion_detalle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='superficie_rodadura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='superficie_rodadura_otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='utilizacion_vial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
