# Generated by Django 5.0 on 2025-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0184_ipat_alineacion_horizontal_ipat_alineacion_vertical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipat',
            name='hipotesis_audio',
        ),
        migrations.RemoveField(
            model_name='ipat',
            name='hipotesis_text',
        ),
        migrations.RemoveField(
            model_name='ipat',
            name='lugar_impacto_imagenes',
        ),
        migrations.RemoveField(
            model_name='ipat',
            name='lugar_impacto_texto',
        ),
        migrations.RemoveField(
            model_name='ipat',
            name='victimas',
        ),
        migrations.AddField(
            model_name='ipat',
            name='interrogatorio_conductor',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
