# Generated by Django 5.0 on 2025-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0185_remove_ipat_hipotesis_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipat',
            name='hipotesis_conductor',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ipat',
            name='hipotesis_pasajero',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ipat',
            name='hipotesis_peaton',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ipat',
            name='hipotesis_vehiculo',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ipat',
            name='hipotesis_via',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
