# Generated by Django 5.0 on 2025-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0186_ipat_hipotesis_conductor_ipat_hipotesis_pasajero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipat',
            name='hipotesis_conductor',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='hipotesis_pasajero',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='hipotesis_peaton',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='hipotesis_vehiculo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='hipotesis_via',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='impact_visual',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='impact_visual_lines',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='testigos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
