# Generated by Django 5.0 on 2025-04-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0187_alter_ipat_hipotesis_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipat',
            name='caracteristica_via',
        ),
    ]
