# Generated by Django 5.0 on 2025-05-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0188_remove_ipat_caracteristica_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='empresaAdministra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_administrados', to='myapp.empresas'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='empresaOficial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_oficiales', to='myapp.empresas'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nivelServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.nivelservicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipoOperacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tipooperacion'),
        ),
    ]
