# Generated by Django 5.0 on 2025-05-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0189_alter_servicio_empresaadministra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoVehiculo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnicaHomologacionCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('soporte', models.CharField(blank=True, max_length=299, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('excel_documento_id', models.IntegerField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_homologacion_carroceria', to='myapp.vehiculos')),
            ],
            options={
                'ordering': ['vehiculo', '-fecha_expedicion'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaHomologacionChasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('soporte', models.CharField(blank=True, max_length=299, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('excel_documento_id', models.IntegerField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_homologacion_chasis', to='myapp.vehiculos')),
            ],
            options={
                'ordering': ['vehiculo', '-fecha_expedicion'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaHomologacionVehCarrozado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('soporte', models.CharField(blank=True, max_length=299, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('excel_documento_id', models.IntegerField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_homologacion_veh_carrozado', to='myapp.vehiculos')),
            ],
            options={
                'ordering': ['vehiculo', '-fecha_expedicion'],
            },
        ),
        migrations.CreateModel(
            name='LicenciaTransitoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=100)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('soporte', models.CharField(blank=True, max_length=299, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('excel_documento_id', models.IntegerField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias_transito_docs', to='myapp.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='PolizaContractual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100)),
                ('aseguradora_nombre_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('soporte', models.CharField(blank=True, max_length=299, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('excel_documento_id', models.IntegerField(blank=True, null=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.aseguradora')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas_contractuales', to='myapp.vehiculos')),
            ],
            options={
                'ordering': ['vehiculo', '-fecha_fin_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='PolizaExtracontractual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100)),
                ('aseguradora_nombre_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('soporte', models.CharField(blank=True, max_length=299, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('excel_documento_id', models.IntegerField(blank=True, null=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.aseguradora')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas_extracontractuales', to='myapp.vehiculos')),
            ],
            options={
                'ordering': ['vehiculo', '-fecha_fin_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='PolizaTodoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100)),
                ('aseguradora_nombre_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('soporte', models.CharField(blank=True, max_length=299, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('excel_documento_id', models.IntegerField(blank=True, null=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.aseguradora')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas_todo_riesgo', to='myapp.vehiculos')),
            ],
            options={
                'ordering': ['vehiculo', '-fecha_fin_vigencia'],
            },
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacioncarroceria',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'numero_documento', 'fecha_expedicion'), name='unique_ft_carroceria_doc_date_v2'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacioncarroceria',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento__isnull', True)), fields=('vehiculo', 'soporte'), name='unique_ft_carroceria_support_v2'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionchasis',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'numero_documento', 'fecha_expedicion'), name='unique_ft_chasis_doc_date_v2'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionchasis',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento__isnull', True)), fields=('vehiculo', 'soporte'), name='unique_ft_chasis_support_v2'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionvehcarrozado',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'numero_documento', 'fecha_expedicion'), name='unique_ft_vehcarroz_doc_date_v2'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionvehcarrozado',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento__isnull', True)), fields=('vehiculo', 'soporte'), name='unique_ft_vehcarroz_support_v2'),
        ),
        migrations.AlterUniqueTogether(
            name='polizacontractual',
            unique_together={('vehiculo', 'numero_poliza', 'fecha_fin_vigencia')},
        ),
        migrations.AlterUniqueTogether(
            name='polizaextracontractual',
            unique_together={('vehiculo', 'numero_poliza', 'fecha_fin_vigencia')},
        ),
        migrations.AlterUniqueTogether(
            name='polizatodoriesgo',
            unique_together={('vehiculo', 'numero_poliza', 'fecha_fin_vigencia')},
        ),
    ]
