# Generated by Django 5.0 on 2025-05-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0190_aseguradora_tipodocumentovehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciatransitodoc',
            name='vehiculo',
        ),
        migrations.AlterModelOptions(
            name='licenciatransito',
            options={'ordering': ['vehiculo', '-fecha_expedicion']},
        ),
        migrations.AlterModelOptions(
            name='revisiontecnomecanica',
            options={'ordering': ['vehiculo', '-fecha_vencimiento']},
        ),
        migrations.AlterModelOptions(
            name='soat',
            options={'ordering': ['vehiculo', '-vigencia_hasta']},
        ),
        migrations.AlterModelOptions(
            name='tarjetaoperacion',
            options={'ordering': ['vehiculo', '-fechaFinVigencia']},
        ),
        migrations.RemoveConstraint(
            model_name='fichatecnicahomologacioncarroceria',
            name='unique_ft_carroceria_doc_date_v2',
        ),
        migrations.RemoveConstraint(
            model_name='fichatecnicahomologacioncarroceria',
            name='unique_ft_carroceria_support_v2',
        ),
        migrations.RemoveConstraint(
            model_name='fichatecnicahomologacionchasis',
            name='unique_ft_chasis_doc_date_v2',
        ),
        migrations.RemoveConstraint(
            model_name='fichatecnicahomologacionchasis',
            name='unique_ft_chasis_support_v2',
        ),
        migrations.RemoveConstraint(
            model_name='fichatecnicahomologacionvehcarrozado',
            name='unique_ft_vehcarroz_doc_date_v2',
        ),
        migrations.RemoveConstraint(
            model_name='fichatecnicahomologacionvehcarrozado',
            name='unique_ft_vehcarroz_support_v2',
        ),
        migrations.RenameField(
            model_name='licenciatransito',
            old_name='numero',
            new_name='numero_documento',
        ),
        migrations.AlterUniqueTogether(
            name='licenciatransito',
            unique_together={('vehiculo', 'numero_documento')},
        ),
        migrations.AddField(
            model_name='fichatecnicahomologacioncarroceria',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='fichatecnicahomologacionchasis',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='fichatecnicahomologacionvehcarrozado',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='licenciatransito',
            name='excel_documento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenciatransito',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenciatransito',
            name='fecha_fin_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenciatransito',
            name='fecha_inicio_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenciatransito',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='polizacontractual',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='polizaextracontractual',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='polizatodoriesgo',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='revisiontecnomecanica',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.aseguradora'),
        ),
        migrations.AddField(
            model_name='revisiontecnomecanica',
            name='excel_documento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisiontecnomecanica',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='soat',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.aseguradora'),
        ),
        migrations.AddField(
            model_name='soat',
            name='aseguradora_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soat',
            name='excel_documento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soat',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AddField(
            model_name='tarjetaoperacion',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.aseguradora'),
        ),
        migrations.AddField(
            model_name='tarjetaoperacion',
            name='excel_documento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjetaoperacion',
            name='tipo_documento_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocumentovehiculo'),
        ),
        migrations.AlterField(
            model_name='fichatecnicahomologacioncarroceria',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnicahomologacionchasis',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnicahomologacionvehcarrozado',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='licenciatransito',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='licenciatransito',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='licenciatransito',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias_transito_docs', to='myapp.vehiculos'),
        ),
        migrations.AlterField(
            model_name='polizacontractual',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='polizaextracontractual',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='polizatodoriesgo',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='revisiontecnomecanica',
            name='placa',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='revisiontecnomecanica',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='revisiontecnomecanica',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_tecnomecanicas', to='myapp.vehiculos'),
        ),
        migrations.AlterField(
            model_name='soat',
            name='placa',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='soat',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='soat',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soat_docs', to='myapp.vehiculos'),
        ),
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='soporte',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_operacion', to='myapp.vehiculos'),
        ),
        migrations.AlterUniqueTogether(
            name='revisiontecnomecanica',
            unique_together={('vehiculo', 'no_certificado', 'fecha_vencimiento')},
        ),
        migrations.AlterUniqueTogether(
            name='soat',
            unique_together={('vehiculo', 'numero_poliza', 'vigencia_hasta')},
        ),
        migrations.AlterUniqueTogether(
            name='tarjetaoperacion',
            unique_together={('vehiculo', 'numero', 'fechaFinVigencia')},
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacioncarroceria',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'numero_documento', 'fecha_expedicion'), name='unique_ft_carroceria_doc_date_v3'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacioncarroceria',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento__isnull', True)), fields=('vehiculo', 'soporte'), name='unique_ft_carroceria_support_v3'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionchasis',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'numero_documento', 'fecha_expedicion'), name='unique_ft_chasis_doc_date_v3'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionchasis',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento__isnull', True)), fields=('vehiculo', 'soporte'), name='unique_ft_chasis_support_v3'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionvehcarrozado',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'numero_documento', 'fecha_expedicion'), name='unique_ft_vehcarroz_doc_date_v3'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicahomologacionvehcarrozado',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento__isnull', True)), fields=('vehiculo', 'soporte'), name='unique_ft_vehcarroz_support_v3'),
        ),
        migrations.DeleteModel(
            name='LicenciaTransitoDoc',
        ),
        migrations.RemoveField(
            model_name='licenciatransito',
            name='fechaExpedicion',
        ),
        migrations.RemoveField(
            model_name='licenciatransito',
            name='fechaFinVigencia',
        ),
        migrations.RemoveField(
            model_name='licenciatransito',
            name='fechaInicialVigencia',
        ),
    ]
