# Generated by Django 5.0 on 2025-05-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0191_remove_licenciatransitodoc_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVencimientosDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('datos_reporte', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_vencimientos', to='myapp.empresas')),
            ],
            options={
                'ordering': ['empresa', '-fecha_reporte'],
                'unique_together': {('empresa', 'fecha_reporte')},
            },
        ),
    ]
