# Generated by Django 5.0 on 2025-05-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0192_reportevencimientosdiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventolegal',
            name='merged_pdf',
        ),
    ]
