# Generated by Django 5.0 on 2025-05-12 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0193_remove_eventolegal_merged_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='identificacion',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revisiontecnomecanica',
            name='fecha_expedicion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='revisiontecnomecanica',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='revisiontecnomecanica',
            name='no_certificado',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nivelServicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.nivelservicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='numeroInterno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria'),
        ),
        migrations.AlterField(
            model_name='soat',
            name='fecha_expedicion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='soat',
            name='vigencia_desde',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='soat',
            name='vigencia_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='fechaExpedicion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='fechaFinVigencia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='fechaInicialVigencia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjetaoperacion',
            name='numero',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculopropietario',
            name='porcentaje',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiculotenedor',
            name='porcentaje',
            field=models.IntegerField(null=True),
        ),
    ]
