# Generated by Django 5.0 on 2025-05-15 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0194_alter_propietario_identificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('codigoProceso', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='numero_victimas',
        ),
        migrations.CreateModel(
            name='EtapaDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigoEtapa', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('proceso_definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='myapp.procesodefinicion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('proceso_definicion', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='SubEtapaDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigoSubEtapa', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('etapa_definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_etapas', to='myapp.etapadefinicion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('etapa_definicion', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ActuacionDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('terminaProceso', models.BooleanField(default=False)),
                ('estadoResultado', models.CharField(blank=True, max_length=100, null=True)),
                ('codigoActuacion', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('sub_etapa_definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='myapp.subetapadefinicion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('sub_etapa_definicion', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('herido', 'Herido'), ('fatal', 'Fatal')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=20)),
                ('nombreContacto', models.CharField(blank=True, max_length=255, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victimas', to='myapp.siniestro')),
            ],
        ),
        migrations.CreateModel(
            name='VictimaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_general', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_progreso', 'En Progreso'), ('terminado', 'Terminado')], default='no_iniciado', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actuacion_definicion_siguiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.actuaciondefinicion')),
                ('etapa_definicion_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.etapadefinicion')),
                ('proceso_definicion_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.procesodefinicion')),
                ('sub_etapa_definicion_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.subetapadefinicion')),
                ('victima', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceso_estado', to='myapp.victima')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialActuacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_actuacion', models.DateField()),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_actuaciones/')),
                ('documento_nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('status_actuacion', models.CharField(choices=[('completada', 'Completada'), ('omitida_temporalmente', 'Omitida Temporalmente'), ('omitida_permanentemente', 'Omitida Permanentemente'), ('en_espera', 'En Espera'), ('pendiente', 'Pendiente')], max_length=30)),
                ('actuacion_definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.actuaciondefinicion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resuelve_omision_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accion_resolutoria', to='myapp.historialactuacion')),
                ('victima_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_actuaciones', to='myapp.victimaproceso')),
            ],
        ),
    ]
