# Generated by Django 5.0 on 2025-05-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0196_alter_actuaciondefinicion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soat',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='DocumentoSiniestroHistorialActuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_actuaciones_siniestros/')),
                ('documento_nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('siniestro_historial_actuacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='myapp.siniestrohistorialactuacion')),
            ],
        ),
    ]
