# Generated by Django 5.0 on 2025-05-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0197_alter_soat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenciatransito',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='polizacontractual',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='polizaextracontractual',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='polizatodoriesgo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reportevencimientosdiario',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='revisiontecnomecanica',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tarjetaoperacion',
            unique_together=set(),
        ),
    ]
