# Generated by Django 5.0 on 2025-06-04 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0201_vehiculolog_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropietarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('instancia_pk', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.propietario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propietario_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
