# Generated by Django 5.0 on 2025-06-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0202_propietariolog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='carroceria',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='combustible',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='entidad_expide_certificado',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='radio_accion',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='tarjetaoperacion',
            name='servicio',
        ),
    ]
