# Generated by Django 5.0 on 2025-06-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0203_remove_tarjetaoperacion_carroceria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='ciudad',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='departamento',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
