# Generated by Django 5.0 on 2025-06-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0204_propietario_ciudad_propietario_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipat',
            name='caracteristicas_lugar',
        ),
        migrations.RemoveField(
            model_name='ipat',
            name='tipo_zona_urbana',
        ),
        migrations.RemoveField(
            model_name='ipat',
            name='zona_escolar',
        ),
        migrations.RemoveField(
            model_name='licenciatransito',
            name='tipo_documento_vehiculo',
        ),
        migrations.AddField(
            model_name='ipat',
            name='area',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='croquis_lines',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='sector',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='ipat',
            name='zona',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ipat',
            name='condicion_climatica',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
