# Generated by Django 5.0 on 2025-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0205_remove_ipat_caracteristicas_lugar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='correo_conductor',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='direccion_conductor',
        ),
        migrations.AddField(
            model_name='tercero',
            name='cedula_propietario',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
