# Generated by Django 5.0 on 2025-06-11 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0206_remove_tercero_conductor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestromedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siniestromedia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
