# Generated by Django 5.0 on 2025-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0207_siniestromedia_created_at_siniestromedia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='licencia_conduccion',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='licencias/'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='licencia_transito',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='licencias/'),
        ),
    ]
