# Generated by Django 5.0 on 2025-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0208_alter_tercero_licencia_conduccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculolog',
            name='accion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehiculolog',
            name='instancia_pk',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehiculolog',
            name='modelo_afectado',
            field=models.CharField(max_length=200),
        ),
    ]
