# Generated by Django 5.0 on 2025-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0209_alter_vehiculolog_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventolegal',
            name='tipo_evento',
            field=models.CharField(choices=[('MATRICULA', 'Matrícula'), ('TRASPASO', 'Traspaso'), ('REGRABACION_MOTOR', 'Regrabación de motor'), ('REGRABACION_CHASIS', 'Regrabación de chasis'), ('DUPLICADO_LICENCIA', 'Duplicado de licencia'), ('DUPLICADO_PLACAS', 'Duplicado de placas'), ('INSCRIPCION_PRENDA', 'Inscripción de prenda'), ('LEVANTAR_PRENDA', 'Levantamiento de prenda'), ('CAMBIO_MOTOR', 'Cambio de motor'), ('DESVINCULACION', 'Desvinculación')], max_length=50),
        ),
    ]
