# Generated by Django 5.0 on 2025-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0210_alter_eventolegal_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='chasis',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
