# Generated by Django 5.0 on 2025-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0211_alter_vehiculos_chasis'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
